Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'spec/dummy/**/*'
    - 'spec/fixtures/**/*'
    - 'config/header.rb'
